H&M Product data - Exploratory Data Analysis

In [45]:
#Importing Libraries
import numpy as np
import pandas as pd
import os
from pathlib import Path

In [2]:
data_dir = Path('../input/raw')

In [3]:
#To preserve the zeros in the article_id column, we will read the csv file with dtype argument as str
articles_df = pd.read_csv(data_dir/'articles.csv', dtype={"article_id": str})
customers_df = pd.read_csv(data_dir/'customers.csv', dtype={"customer_id": str})
sample_submission_df = pd.read_csv(data_dir/'sample_submission.csv')
transactions_df = pd.read_csv(data_dir/'transactions_train.csv', dtype={"article_id": str, "customer_id": str}, parse_dates=["t_dat"])

#### Article Analysis

Because of the huge execution time it takes, 'article_id' is converted to integer. Before submission this will be reverted back.

In [4]:
articles_df['article_id'] = articles_df['article_id'].astype('int32')
transactions_df['article_id'] = transactions_df['article_id'].astype('int32')

In [5]:
articles_df.head()

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."

In [6]:
articles_df.shape

(105542, 25)

There are 105,542 fashions items available. Each item has 25 features.

In [7]:
articles_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105542 entries, 0 to 105541
Data columns (total 25 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   article_id                    105542 non-null  int32
 1   product_code                  105542 non-null  int64
 2   prod_name                     105542 non-null  object
 3   product_type_no               105542 non-null  int64
 4   product_type_name             105542 non-null  object
 5   product_group_name            105542 non-null  object
 6   graphical_appearance_no       105542 non-null  int64
 7   graphical_appearance_name     105542 non-null  object
 8   colour_group_code             105542 non-null  int64
 9   colour_group_name             105542 non-null  object
 10  perceived_colour_value_id     105542 non-null  int64
 11  perceived_colour_value_name   105542 non-null  object
 12  perceived_colour_master_id    105542 non-null  int64
 13  perceived_colour_master_name  105542 non-null  object
 14  department_no                 105542 non-null  int64
 15  department_name               105542 non-null  object
 16  index_code                    105542 non-null  object
 17  index_name                    105542 non-null  object
 18  index_group_no                105542 non-null  int64
 19  index_group_name              105542 non-null  object
 20  section_no                    105542 non-null  int64
 21  section_name                  105542 non-null  object
 22  garment_group_no              105542 non-null  int64
 23  garment_group_name            105542 non-null  object
 24  detail_desc                   105126 non-null  object
dtypes: int32(1), int64(10), object(14)
memory usage: 19.7+ MB

In [8]:
articles_df.isnull().sum()

article_id                        0
product_code                      0
prod_name                         0
product_type_no                   0
product_type_name                 0
product_group_name                0
graphical_appearance_no           0
graphical_appearance_name         0
colour_group_code                 0
colour_group_name                 0
perceived_colour_value_id         0
perceived_colour_value_name       0
perceived_colour_master_id        0
perceived_colour_master_name      0
department_no                     0
department_name                   0
index_code                        0
index_name                        0
index_group_no                    0
index_group_name                  0
section_no                        0
section_name                      0
garment_group_no                  0
garment_group_name                0
detail_desc                     416
dtype: int64

There is 416 missing values in the "detail_desc" column. This is not very important feature to handle the missing data

#### Customer Data Analysis

In [9]:
customers_df.head()

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,NaN,ACTIVE,NONE,54.0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...

In [10]:
customers_df.shape

(1371980, 7)

There are 1,371,980 customer records with 7 features each.

In [11]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1371980 entries, 0 to 1371979
Data columns (total 7 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   customer_id             1371980 non-null  object
 1   FN                      476930 non-null   float64
 2   Active                  464404 non-null   float64
 3   club_member_status      1365918 non-null  object
 4   fashion_news_frequency  1355969 non-null  object
 5   age                     1356119 non-null  float64
 6   postal_code             1371980 non-null  object
dtypes: float64(3), object(4)
memory usage: 73.3+ MB

In [12]:
customers_df.isnull().sum()

customer_id                    0
FN                        895050
Active                    907576
club_member_status          6062
fashion_news_frequency     16011
age                        15861
postal_code                    0
dtype: int64

There is a lot of missing values in the customer_df. We will have to handle them before we can use this data for any analysis or modeling.

#### Transactions Data Analysis

In [13]:
transactions_df.shape

(31788324, 5)

This is a huge data file with 31,788,324 transaction and 5 features.

In [14]:
transactions_df.head()

,t_dat,customer_id,article_id,price,sales_channel_id
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2
1,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,541518023,0.030492,2
2,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221004,0.015237,2
3,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687003,0.016932,2
4,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687004,0.016932,2

In [15]:
#Timeframe for the transactions data
print("Earliest transaction date:", transactions_df['t_dat'].min())
print("Latest transaction date:", transactions_df['t_dat'].max())

Earliest transaction date: 2018-09-20 00:00:00
Latest transaction date: 2020-09-22 00:00:00

In [16]:
transactions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31788324 entries, 0 to 31788323
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   t_dat             datetime64[ns]
 1   customer_id       object
 2   article_id        int32
 3   price             float64
 4   sales_channel_id  int64
dtypes: datetime64[ns](1), float64(1), int32(1), int64(1), object(1)
memory usage: 1.1+ GB

In [17]:
transactions_df.isnull().sum()

t_dat               0
customer_id         0
article_id          0
price               0
sales_channel_id    0
dtype: int64

#### Sample Submission Data Analysis

Sample_submission_df holds the sample predictions for each customer. The number of records is same as that of customers_df

In [18]:
sample_submission_df.shape

(1371980, 2)

In [19]:
sample_submission_df.head()

,customer_id,prediction
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0706016001 0706016002 0372860001 0610776002 07...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0706016001 0706016002 0372860001 0610776002 07...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0706016001 0706016002 0372860001 0610776002 07...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0706016001 0706016002 0372860001 0610776002 07...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,0706016001 0706016002 0372860001 0610776002 07...

In [20]:
sample_submission_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1371980 entries, 0 to 1371979
Data columns (total 2 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   customer_id  1371980 non-null  object
 1   prediction   1371980 non-null  object
dtypes: object(2)
memory usage: 20.9+ MB

#### Preprocessing

In [21]:
#Identifying unique customers in each dataframe
print("Unique customers in transactions_df:", transactions_df['customer_id'].nunique())
print("Unique customers in customer_df:", customers_df['customer_id'].nunique()) 
print("Unique customers in sample_submission_df:", sample_submission_df['customer_id'].nunique())

Unique customers in transactions_df: 1362281
Unique customers in customer_df: 1371980
Unique customers in sample_submission_df: 1371980

In [22]:
# Find customers in customers_df that are not in transactions_df
missing_customers = customers_df[~customers_df['customer_id'].isin(transactions_df['customer_id'])]
print(f"Number of customers missing in transactions_df: {len(missing_customers)}")

Number of customers missing in transactions_df: 9699

In [23]:
# Calculate the percentage of customers present in transactions_df
customers_in_transactions = transactions_df['customer_id'].nunique()
percentage = (customers_in_transactions / customers_df['customer_id'].nunique()) * 100

print(f"Percentage of customers in transactions_df: {percentage:.2f}%")

# Calculate the percentage of articles present in transactions_df
articles_in_transactions = transactions_df['article_id'].nunique()
percentage = (articles_in_transactions / articles_df['article_id'].nunique()) * 100

print(f"Percentage of articles in transactions_df: {percentage:.2f}%")

Percentage of customers in transactions_df: 99.29%
Percentage of articles in transactions_df: 99.06%

In [24]:
#Utility Functions for EDA to find missing values and unique values in the dataframes
def missing_data(data):
    """
    missing_data Computes Percentage of Missing Values for the dataframe

    Parameters
    ----------
    data : dataframe
        Dataframe for which the missing value percentages need to be computed.

    Returns
    -------
    missing_df: dataframe
        Dataframe with missing value percentages.
    """
    total = data.isnull().sum().sort_values(ascending=False)
    percent = (data.isnull().sum() / data.isnull().count() * 100).sort_values(
        ascending=False
    )
    missing_df = pd.concat([total, percent], axis=1, keys=["Total", "Percent"])
    return missing_df


def unique_values(data):
    """
    unique_values Computes total and unique value counts per feature.

    Parameters
    ----------
    data : dataframe
        Data for which total and unique value counts per feature need to be calulated.

    Returns
    -------
    tt : dataframe
        Dataframe with total and unique value counts per feature.
    """
    total = data.count()
    tt = pd.DataFrame(total)
    tt.columns = ["Total"]
    uniques = []
    for col in data.columns:
        unique = data[col].nunique()
        uniques.append(unique)
    tt["Uniques"] = uniques
    return tt

##### 1) Article

In [25]:
unique_values(articles_df)

                               Total  Uniques
article_id                    105542   105542
product_code                  105542    47224
prod_name                     105542    45875
product_type_no               105542      132
product_type_name             105542      131
product_group_name            105542       19
graphical_appearance_no       105542       30
graphical_appearance_name     105542       30
colour_group_code             105542       50
colour_group_name             105542       50
perceived_colour_value_id     105542        8
perceived_colour_value_name   105542        8
perceived_colour_master_id    105542       20
perceived_colour_master_name  105542       20
department_no                 105542      299
department_name               105542      250
index_code                    105542       10
index_name                    105542       10
index_group_no                105542        5
index_group_name              105542        5
section_no                    105542       57
section_name                  105542       56
garment_group_no              105542       21
garment_group_name            105542       21
detail_desc                   105126    43404

Most of the categories name match with the id. Except for Product_type and section. We can safely ignore all the 'name' column as the numeric values are high cardinality than the categorical names. Keeping both of them adds redundant information and increases the complexity of the model.

In [26]:
article_columns_to_keep = ['article_id', 'product_code', 'product_type_no', 'product_group_name',  'graphical_appearance_no', 
                     'colour_group_code', 'perceived_colour_value_id', 'perceived_colour_master_id','department_no','index_code', 
                     'index_group_no', 'section_no', 'garment_group_no']
articles_df_cleaned = articles_df[article_columns_to_keep]

In [27]:
missing_data(articles_df_cleaned)

                            Total  Percent
article_id                      0      0.0
product_code                    0      0.0
product_type_no                 0      0.0
product_group_name              0      0.0
graphical_appearance_no         0      0.0
colour_group_code               0      0.0
perceived_colour_value_id       0      0.0
perceived_colour_master_id      0      0.0
department_no                   0      0.0
index_code                      0      0.0
index_group_no                  0      0.0
section_no                      0      0.0
garment_group_no                0      0.0

##### 2) Customers

In [28]:
missing_data(customers_df)

                         Total    Percent
Active                  907576  66.150819
FN                      895050  65.237831
fashion_news_frequency   16011   1.167000
age                      15861   1.156066
club_member_status        6062   0.441843
customer_id                  0   0.000000
postal_code                  0   0.000000

There are missing values in Active, FN, fashion_news_frequency, age and club_member_status column

In [29]:
unique_values(customers_df)

                          Total  Uniques
customer_id             1371980  1371980
FN                       476930        1
Active                   464404        1
club_member_status      1365918        3
fashion_news_frequency  1355969        3
age                     1356119       84
postal_code             1371980   352899

In [30]:
customers_df["fashion_news_frequency"].unique()

array(['NONE', 'Regularly', nan, 'Monthly'], dtype=object)

In [31]:
customers_df["fashion_news_frequency"] = customers_df["fashion_news_frequency"].fillna('NONE')

In [32]:
print(customers_df['club_member_status'].value_counts())
print(customers_df['club_member_status'].unique())

club_member_status
ACTIVE        1272491
PRE-CREATE      92960
LEFT CLUB         467
Name: count, dtype: int64
['ACTIVE' nan 'PRE-CREATE' 'LEFT CLUB']

Customers in Pre-create , Left club, missing values status could be considered "InActive"

In [33]:
customers_df["club_member_status"] = customers_df["club_member_status"].fillna('INACTIVE')
customers_df["club_member_status"] = customers_df["club_member_status"].replace(["PRE-CREATE"], "INACTIVE")
customers_df["club_member_status"] = customers_df["club_member_status"].replace(["LEFT CLUB"], "INACTIVE")

In [34]:
customers_df["FN"] = customers_df["FN"].fillna(0)
customers_df["FN"] = customers_df["FN"].astype(int)

In [35]:
customers_df["age"] = customers_df["age"].fillna(customers_df["age"].median())

Since 'Active' column has many missing data, also customer active status is indicated by 'club_member_status'. This column can be dropped

In [36]:
customer_columns_to_keep = ['customer_id', 'FN', 'club_member_status', 'fashion_news_frequency',  'age']
customers_df_cleaned = customers_df[customer_columns_to_keep]

In [37]:
missing_data(customers_df_cleaned)

                        Total  Percent
customer_id                 0      0.0
FN                          0      0.0
club_member_status          0      0.0
fashion_news_frequency      0      0.0
age                         0      0.0

##### 3) Transactions

In [38]:
transactions_df_cleaned = transactions_df

# Change t_dat to date type
transactions_df_cleaned['t_dat'] = pd.to_datetime(transactions_df_cleaned['t_dat'], format="%Y-%m-%d")

In [39]:
missing_data(transactions_df_cleaned)

                  Total  Percent
t_dat                 0      0.0
customer_id           0      0.0
article_id            0      0.0
price                 0      0.0
sales_channel_id      0      0.0

### Split into Training and Validation Data

In [40]:
def create_temporal_split(transactions_df):
    """
    Splits transactions into a local training set and a 7-day local validation target window.
    """
    
    # Find the maximum date 
    max_date = transactions_df['t_dat'].max()
    
    # 7-day validation target window 
    val_end_date = max_date
    val_start_date = max_date - pd.Timedelta(days=6) 
    
    # training cutoff 
    train_end_date = val_start_date - pd.Timedelta(days=1)
    
    print(f"Training data: From beginning up to {train_end_date.strftime('%Y-%m-%d')}")
    print(f"Validation target window: {val_start_date.strftime('%Y-%m-%d')} to {val_end_date.strftime('%Y-%m-%d')}")
    
    # Split the transactions
    train_df = transactions_df[transactions_df['t_dat'] <= train_end_date]
    val_target_df = transactions_df[
        (transactions_df['t_dat'] >= val_start_date) & 
        (transactions_df['t_dat'] <= val_end_date)
    ]
    
    return train_df, val_target_df

In [41]:
trans_train, trans_val = create_temporal_split(transactions_df_cleaned)

Training data: From beginning up to 2020-09-15
Validation target window: 2020-09-16 to 2020-09-22

In [ ]:
def save_transactions_as_parquet(df, cleaned_df_name):
    cleaned_df_folder = "../input/cleaned"
    
    # Create the directory if it doesn't exist
    os.makedirs(cleaned_df_folder, exist_ok=True)
    # Save as parquet
    df.to_parquet(cleaned_df_folder + "/" + cleaned_df_name + ".parquet", index=False)
    
    
    print("Parquet files successfully saved in '" + cleaned_df_folder + "'!")
    
def load_from_parquet(cleaned_df_name):
    print("Loading data from Parquet...")
    cleaned_df_folder = "input/cleaned"
    return pd.read_parquet(cleaned_df_folder + "/" + cleaned_df_name + ".parquet")

In [48]:
save_transactions_as_parquet(trans_train, "train_transactions")
save_transactions_as_parquet(trans_val, "val_transactions")

Parquet files successfully saved in 'input/cleaned'!
Parquet files successfully saved in 'input/cleaned'!